### ISSUE TITLE
Unicode characters in filenames causes unpredictable behavior in local and remote clients

### ISSUE THREAD

**Issue by RomanHargrave** [Syncplay/syncplay#135]
Text in filename found to be causing the problem: `³`.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/home/roman/.local/opt/syncplay-1.4.0/syncplay/vendor/qt4reactor.py", line 102, in _read
    self.reactor._iterate(fromqt=True)
  File "/home/roman/.local/opt/syncplay-1.4.0/syncplay/vendor/qt4reactor.py", line 231, in _iterate
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 801, in runUntilCurrent
    f(*a, **kw)
  File "/home/roman/.local/opt/syncplay-1.4.0/syncplay/client.py", line 461, in updateFile
    self.fileSwitch.notifyUserIfFileNotInMediaDirectory(filename, path)
  File "/home/roman/.local/opt/syncplay-1.4.0/syncplay/client.py", line 1820, in notifyUserIfFileNotInMediaDirectory
    self._client.ui.showErrorMessage(getMessage("added-file-not-in-media-directory-error").format(directoryToFind))
exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 57: ordinal not in range(128)
```

**Comment by Et0h** [comment]
Thanks for reporting this issue. Hopefully the problem has now been fixed and the fix doesn't create new problems.
