### ISSUE TITLE
Error Creating Managed Room Syncplay 1.6.0

### ISSUE THREAD

**Issue by jonipin** [Syncplay/syncplay#205]
After following this Guide https://blog.cybrox.eu/posts/setup-a-proper-syncplay-server-on-ubuntu-debian
I tried to Create a Managed room and got this error PLS SEND HELP:

Welcome to Syncplay server, ver. 1.6.0
PLEASE NOTE: To allow room operator passwords generated by this server instance to still work when the server is restarted, please add the following command line argument when running the Syncplay server in the future: --salt CKYCBAXEKZ
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/syncplay/syncplay/protocols.py", line 43, in lineReceived
    self.handleMessages(messages)
  File "/usr/lib/syncplay/syncplay/protocols.py", line 21, in handleMessages
    self.handleSet(message[1])
  File "/usr/lib/syncplay/syncplay/protocols.py", line 324, in wrapper
    return f(self, *args, **kwds)
  File "/usr/lib/syncplay/syncplay/protocols.py", line 441, in handleSet
    self._factory.authRoomController(self._watcher, password, room)
  File "/usr/lib/syncplay/syncplay/server.py", line 166, in authRoomController
    newName = RoomPasswordProvider.getControlledRoomName(roomName, password, self._salt)
  File "/usr/lib/syncplay/syncplay/utils.py", line 474, in getControlledRoomName
    return "+" + roomName + ":" + RoomPasswordProvider._computeRoomHash(roomName, password, salt)
  File "/usr/lib/syncplay/syncplay/utils.py", line 479, in _computeRoomHash
    salt = hashlib.sha256(salt).hexdigest()
builtins.TypeError: Unicode-objects must be encoded before hashing

**Comment by Et0h** [comment]
Thank you for reporting this issue which I have now confirmed.

Please run Syncplay 1.5.5 server until this issue is resolved: https://syncplay.pl/syncplay-1-5-5/

**Comment by jonipin** [comment]
Thanks :D

**Comment by Et0h** [comment]
Early access to Syncplay 1.6.1 which should also fix the issue: https://bintray.com/syncplay/Syncplay/Syncplay/v1.6.1#files

**Comment by jonipin** [comment]
As soon as you acknowledged the error and fixed the file in question i downloaded it and replaced the defective file in my 1.6.0 install and everything started Working Thank You.
Btw yesterday i noticed the error in the code but since i'm a junior coder i didnt know if you wanted any advice on the matter but i looked in the Code and my suspicions were correct: 
_roomName = roomName.encode('utf8')
salt = salt.encode('utf8')
password = password.encode('utf8')_
Thank you again for the fast response :D

**Comment by Et0h** [comment]
> Btw yesterday i noticed the error in the code but since i'm a junior coder i didnt know if you wanted any advice on the matter but i looked in the Code and my suspicions were correct:

I learned Python just so I could work on Syncplay so junior coders are always welcome to contribute. Everyone who works on Syncplay does so as a hobby, and it is the more the merrier when it comes to contributors - be that bug reports, solution suggestions, or indeed letting us know when things are working fine.

**Comment by Et0h** [comment]
Issue should be resolved in Syncplay 1.6.0: https://syncplay.pl/syncplay-1-6-1/
