### ISSUE TITLE
“ImportError: No module named PySide” despite --no-gui

### ISSUE THREAD

**Issue by haasn** [Syncplay/syncplay#26]
Hey,

As the title describes, the client fails to run without PySide installed despite passing --no-gui. Also, if I install PySide without pulling in its Qt backend, I still get import errors on QtGui (again, despite --no-gui).

**Comment by devmsv** [comment]
Hi, is there a build flag to disable gui support?

I'm getting this with the last relase:

```sh
sirius$ syncplay --no-gui
```
```python
Traceback (most recent call last):
  File "/usr/local/bin/syncplay", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyside2>=5.12.0' distribution was not found and is required by syncplay
```

**Comment by devmsv** [comment]
Hi, I'm facing the same issue, please reopen the issue. see my reply above

**Comment by devmsv** [comment]
Any updates on this? Do you need some more debbuging from my side?

**Comment by daniel-123** [comment]
@devmsv I've just tried out to replicate the issue on my side without success.

With removed pyside2 calling basic `syncplay` command starts it in CLI mode with complaint about being unable to find PySide. With `--no-gui` switch it works as I'd expect it to.

What are the versions of Syncplay, OS, pyside etc. you are seeing the problem with?

**Comment by devmsv** [comment]
Hi Daniel,


syncplay: 1.6.4a
os: OpenBSD -current (I'm porting syncplay to OpenBSD)

I have build syncplay without PySide. listed as depency only for gui and we don't have it ported.

regards,

**Comment by daniel-123** [comment]
I see no obvious reasons for why it would behave differently to my machine (Debian 11, python 3.8, current git HEAD of Syncplay).

I'm not familiar with OpenBSD, but is it possible to (just for sake of testing) install requirements with pip and check if there is no other issue that just gives non-informative errors? Our "support" for BSD is based pretty much on somebody adjusting the makefile to work there a long time ago and an assumption that it will work because it works on Linux.

Can you also clarify what you mean by "build syncplay without PySide"? We don't have any build process for BSD.

**Comment by devmsv** [comment]
Sorry, this was an old port which was stalled.

I have the following patch applied to build without PySide:


Index: setup.py
--- setup.py.orig
+++ setup.py
@@ -12,8 +12,7 @@ def read(fname):
 if os.getenv('SNAPCRAFT_PART_BUILD', None) is not None:
     installRequirements = ["pyasn1"] + read('requirements.txt').splitlines()
 else:
-    installRequirements = read('requirements.txt').splitlines() +\
-                          read('requirements_gui.txt').splitlines()
+    installRequirements = read('requirements.txt').splitlines()
 
 setuptools.setup(
     name="syncplay",
@@ -34,9 +33,6 @@ setuptools.setup(
     entry_points={
         'console_scripts': [
             'syncplay-server = syncplay.ep_server:main',
-        ],
-        'gui_scripts': [
-            'syncplay = syncplay.ep_client:main',
         ]
     },
     include_package_data=True,

Index: syncplay/ui/__init__.py
--- syncplay/ui/__init__.py.orig
+++ syncplay/ui/__init__.py
@@ -5,10 +5,10 @@ if "QT_PREFERRED_BINDING" not in os.environ:
         ["PySide2", "PySide", "PyQt5", "PyQt4"]
     )
 
-try:
-    from syncplay.ui.gui import MainWindow as GraphicalUI
-except ImportError:
-    pass
+#try:
+#    from syncplay.ui.gui import MainWindow as GraphicalUI
+#except ImportError:
+#    pass
 from syncplay.ui.consoleUI import ConsoleUI
 
without this patches the error is:

Traceback (most recent call last):
File "/usr/local/bin/syncplay", line 6, in <module> from pkg_resources import load_entry_point
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in <module> @_call_aside
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside f(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set working_set = WorkingSet._build_master()
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master ws.require(__requires__)
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require needed = self.resolve(parse_requirements(requirements))
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyside2>=5.12.0' distribution was not found and is required by syncplay

On FreeBSD (diferent OS, but port system is similar) they build it with PySide by default but also without it. I don't now if they have tested without PySide.

I think there is some missing logic on syncplay to ditch PySide if you pass --no-gui. Take into account that you have hardcoded the gui dependecy when its only needed for gui support.

**Comment by daniel-123** [comment]
I tried a fairly "dumb" way of removing the pyside2 dependency from setup.py by literally commenting out the line in requirements_gui.txt.

This resulted in working syncplay CLI interface installed with setuptools. Could you try your build process with just that kind of change?

Another thing I see is that your modification seems to only build the server? From what you sent:
```
-        ],
-        'gui_scripts': [
-            'syncplay = syncplay.ep_client:main',
```
Could that be the actual source of broken client?

**Comment by devmsv** [comment]
Following your suggestion:

```
sirius$ syncplay --no-gui
Traceback (most recent call last):
File "/usr/local/bin/syncplay", line 11, in <module>
  load_entry_point('syncplay==1.6.4', 'gui_scripts', 'syncplay')()
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
  return get_distribution(dist).load_entry_point(group, name)
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
  return ep.load()
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
  return self.resolve()
File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
  module = __import__(self.module_name, fromlist=['__name__'], level=0)
File "/usr/local/lib/python3.7/site-packages/syncplay/ep_client.py", line 3, in <module>
  from syncplay.clientManager import SyncplayClientManager
File "/usr/local/lib/python3.7/site-packages/syncplay/clientManager.py", line 4, in <module>
  from syncplay.ui.ConfigurationGetter import ConfigurationGetter
File "/usr/local/lib/python3.7/site-packages/syncplay/ui/ConfigurationGetter.py", line 12, in <module>
  from syncplay.players.playerFactory import PlayerFactory
File "/usr/local/lib/python3.7/site-packages/syncplay/players/__init__.py", line 3, in <module>
  from syncplay.players.vlc import VlcPlayer
File "/usr/local/lib/python3.7/site-packages/syncplay/players/vlc.py", line 22, in <module>
  class VlcPlayer(BasePlayer):
File "/usr/local/lib/python3.7/site-packages/syncplay/players/vlc.py", line 31, in VlcPlayer
  SLAVE_ARGS.extend(constants.VLC_SLAVE_EXTRA_ARGS)
TypeError: 'NoneType' object is not iterable
sirius$ cat p
patches/  pkg/

sirius$ cat patches/patch-setup_py

$OpenBSD$

Index: setup.py
--- setup.py.orig
+++ setup.py
@@ -12,8 +12,7 @@ def read(fname):
if os.getenv('SNAPCRAFT_PART_BUILD', None) is not None:
installRequirements = ["pyasn1"] + read('requirements.txt').splitlines()
else:
-    installRequirements = read('requirements.txt').splitlines() +\
-                          read('requirements_gui.txt').splitlines()
+    installRequirements = read('requirements.txt').splitlines()

setuptools.setup(
name="syncplay",
```

Maybe is something about our build-infrastrcture that I don't know (first python port I made)?
I will try to get help on openbsd-wip repo.

regards,

**Comment by daniel-123** [comment]
I don't know how BSD ports work in detail, but Syncplay can be installed with make (without using setuptools). That was also the original way installation on BSD worked, so it might be an avenue worth considering.

**Comment by daniel-123** [comment]
@devmsv: After rethinking it - the original issue was different from what you found and it was fixed.

If you still have problems with packaging Syncplay on BSD, you'll need to open another issue. Just keep in mind that no one from usual Syncplay developers is knowledgable about BSD or its packaging, so the amount of help we can provide is limited.
