### ISSUE TITLE
Syncplay 1.6.6 Beta 1 - Crash On Launch (storeControlPassword)

### ISSUE THREAD

**Issue by jimmydorry** [Syncplay/syncplay#357]
OS: Windows 10
Syncplay: Syncplay 1.6.6 Beta 1
Microsoft Visual C++ 2015 Redistributable Package Installed: Yes

``````
Traceback (most recent call last):
  File "syncplayClient.py", line 17, in <module>
  File "C:\projects\syncplay\syncplay\ep_client.py", line 8, in main
  File "C:\projects\syncplay\syncplay\clientManager.py", line 13, in run
  File "C:\projects\syncplay\syncplay\client.py", line 100, in __init__
  File "C:\projects\syncplay\syncplay\client.py", line 697, in setRoom
  File "C:\projects\syncplay\syncplay\client.py", line 1045, in storeControlPassword
AttributeError: 'SyncplayClient' object has no attribute '_config'
```````````

**Comment by jimmydorry** [comment]
My default configuration is a self managed room with a password.

I can reproduce this issue when trying to run other rooms like:

+testingroom:3A0458B75EC6:NM-962-445

**Comment by Et0h** [comment]
Thanks @jimmydorry for the clear instructions.

I could reproduce the issue and it should now be fixed in the latest build which will soon be available from https://bintray.com/syncplay/Syncplay/Syncplay/v1.6.6#files

Once the Updated time changes to today, try it out and let me know if it works..

**Comment by jimmydorry** [comment]
No crash, and it authenticates without issue. Great work!
