### ISSUE TITLE
Windows 10: MPV process retry limit reached

### ISSUE THREAD

**Issue by dutchgecko** [Syncplay/syncplay#390]
Whenever trying to run MPV through Syncplay I get the following error:

![image](https://user-images.githubusercontent.com/2513484/107851492-b3c9b080-6e0a-11eb-8a2d-f40910b6e48f.png)

Logfile:

    MPV start failed.
    Traceback (most recent call last):
      File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 456, in _start_mpv
      File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 211, in __init__
      File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 228, in _start_process
    syncplay.vendor.python_mpv_jsonipc.python_mpv_jsonipc.MPVError: MPV start timed out.
    MPV start failed.
    Traceback (most recent call last):
      File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 456, in _start_mpv
      File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 211, in __init__
      File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 228, in _start_process
    syncplay.vendor.python_mpv_jsonipc.python_mpv_jsonipc.MPVError: MPV start timed out.
    MPV start failed.
    Traceback (most recent call last):
      File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 456, in _start_mpv
      File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 211, in __init__
      File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 228, in _start_process
    syncplay.vendor.python_mpv_jsonipc.python_mpv_jsonipc.MPVError: MPV start timed out.

I have MPV v0.33 installed via scoop.

I saw [this issue](https://github.com/iwalton3/python-mpv-jsonipc/issues/2) on the python-mpv-jsonipc tracker but that fix appears to have been vendored in so this looks like a different problem.

I was previously using MPC-HC, which worked fine.

**Comment by Et0h** [comment]
Does this issue exist with the 1.6.8 development version of Syncplay: https://bintray.com/syncplay/Syncplay/Syncplay/v1.6.8#files ?

**Comment by dutchgecko** [comment]
That version seems to work perfectly fine, thanks for the link!

**Comment by dutchgecko** [comment]
I spoke too soon. I thought to myself, "better check that 1.6.7 still causes the error," so installed the old version again. As expected, the old version errored. Then I installed the dev version again, and now the error occurs in the dev version too.

So it seems this may be a race condition? Most of the time Syncplay fails to recognise that MPV is running but apparently it can succeed by luck.

**Comment by Et0h** [comment]
Some questions:
1. Where does scoop install mpv to?
2. Are you running on a low-spec PC?
3. If you run Syncplay with --debug do you get any interesting error messages in %APPDATA%\.syncplay.log?
4. Does increasing the number of restarts at https://github.com/Syncplay/syncplay/blob/03cde67c72d401c5c656a6cd2bb55c2da5af8026/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py#L454 and/or adding a short sleep between attempts fix the issue? (Let me know if you need me to build you a version which does this)

**Comment by RivenSkaye** [comment]
Getting the same issue on Arch Linux  Syncplay 1.6.9 grabbed from the AUR (both Syncplay and Syncplay-git).
It starts just fine, then errors out as soon as mpv has to be started.

Tried a fresh mpv install with no config set, but the issue persists.
Plays other links and files just fine.

```
$ uname -a
Linux metang 5.14.2-arch1-2 #1 SMP PREEMPT Thu, 09 Sep 2021 09:42:35 +0000 x86_64 GNU/Linux

$ mpv --version
mpv 0.33.0-336-g62b2c5db98 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Sep 12 13:18:35 CEST 2021
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: n4.4

$ syncplay --version
You're using Syncplay version 1.6.9 (Yoitsu)

$ syncplay
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
MPV failed with returncode 1.
MPV start failed.
Traceback (most recent call last):
  File "/usr/lib/syncplay/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py", line 463, in _start_mpv
    self.mpv_process = MPVProcess(ipc_socket, mpv_location, **kwargs)
  File "/usr/lib/syncplay/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py", line 218, in __init__
    self._start_process(ipc_socket, args, env=env)
  File "/usr/lib/syncplay/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py", line 239, in _start_process
    raise MPVError("MPV not started.")
syncplay.vendor.python_mpv_jsonipc.python_mpv_jsonipc.MPVError: MPV not started.
MPV failed with returncode 1.
MPV start failed.
Traceback (most recent call last):
  File "/usr/lib/syncplay/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py", line 463, in _start_mpv
    self.mpv_process = MPVProcess(ipc_socket, mpv_location, **kwargs)
  File "/usr/lib/syncplay/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py", line 218, in __init__
    self._start_process(ipc_socket, args, env=env)
  File "/usr/lib/syncplay/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py", line 239, in _start_process
    raise MPVError("MPV not started.")
syncplay.vendor.python_mpv_jsonipc.python_mpv_jsonipc.MPVError: MPV not started.
MPV failed with returncode 1.
MPV start failed.
Traceback (most recent call last):
  File "/usr/lib/syncplay/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py", line 463, in _start_mpv
    self.mpv_process = MPVProcess(ipc_socket, mpv_location, **kwargs)
  File "/usr/lib/syncplay/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py", line 218, in __init__
    self._start_process(ipc_socket, args, env=env)
  File "/usr/lib/syncplay/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py", line 239, in _start_process
    raise MPVError("MPV not started.")
syncplay.vendor.python_mpv_jsonipc.python_mpv_jsonipc.MPVError: MPV not started.
```

The same issues happen when launching from LXQT's graphical menus.
Syncplay is located in `/usr/bin/syncplay` and mpv is in `/usr/bin/mpv`.
