### ISSUE TITLE
Could not send quit message: 'MpvPlayer' object has no attribute '_listener'

### ISSUE THREAD

**Issue by JordanPlayz158** [Syncplay/syncplay#509]
**Describe the bug**
This is like #409 but this was not fixed by anything specified in the issue. When I hit "Run Syncplay" the application crashes due to the error above.

**To Reproduce**
1. Be on same OS and Kernel version
2. You can use either the `syncplay` package or compile from source or AppImage, all have the same error
3. Enter in server details and hit "Run Syncplay" or "Store configuration and run Syncplay"
4. See error "Could not send quit message: 'MpvPlayer' object has no attribute '_listener'"

**Expected behavior**
Syncplay opens and I can wait in the room until my friends join and then we start up a video and watch together through syncing.

**Screenshots**

**Version and platform:**
 - OS: Manjaro Linux, Kernel: 5.15.21-1
 - Syncplay version and build type: Syncplay version 1.6.9 (Yoitsu)

**Additional context**
Versions:
```
MPV - 0.34.1-dirty (>= 0.23.0)
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: n4.4.1

Python - 3.10.2 (>= 3.6)
Python-Twisted - 21.7.0-4 (>= 16.4.0)
PySide2 - 5.15.2.1-1 (except for 5.15.0)
Python-Certifi - 2021.10.8-3 (>= 2018.11.29)
Python-PyOpenSSL - 21.0.0-5 (>= 16.0.0)
Python-Service_Identity - 21.1.0-4
Python-IDNA - 3.3-3 (>= 0.6 != 2.3)
```

GUI Logs (With debug enabled):
```
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
[04:25:39 PM] Could not send quit message: 'MpvPlayer' object has no attribute '_listener'
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3.10/site-packages/twisted/python/context.py", line 83, in callWithContext
    return func(*args, **kw)
  File "/usr/lib/syncplay/syncplay/vendor/qt5reactor.py", line 164, in _read
    self.reactor._iterate(fromqt=True)
  File "/usr/lib/syncplay/syncplay/vendor/qt5reactor.py", line 270, in _iterate
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python3.10/site-packages/twisted/internet/base.py", line 967, in runUntilCurrent
    f(*a, **kw)
  File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 662, in callback
    self._startRunCallbacks(result)
  File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 757, in _startRunCallbacks
    raise AlreadyCalledError
twisted.internet.defer.AlreadyCalledError: 

[04:25:40 PM] client/server >> {"TLS": {"startTLS": "send"}}
[04:25:40 PM] client/server << {"TLS": {"startTLS": "true"}}
[04:25:40 PM] client/server >> {"Hello": {"username": "jordan", "password": "cd1a2c444a8517fe1eb25bbf809fa613", "room": {"name": "DITF"}, "version": "1.2.255", "realversion": "1.6.9", "features": {"sharedPlaylists": true, "chat": true, "featureList": true, "readiness": true, "managedRooms": true}}}
[04:25:40 PM] client/server << {"Set": {"ready": {"username": "jordan", "isReady": null, "manuallyInitiated": false}}}
[04:25:40 PM] client/server << {"Set": {"playlistChange": {"user": null, "files": []}}}
[04:25:40 PM] client/server << {"Set": {"playlistIndex": {"user": null, "index": null}}}
[04:25:40 PM] client/server << {"Hello": {"username": "jordan", "room": {"name": "DITF"}, "version": "1.6.9", "realversion": "1.6.9", "motd": "", "features": {"isolateRooms": false, "readiness": true, "managedRooms": true, "chat": true, "maxChatMessageLength": 150, "maxUsernameLength": 150, "maxRoomNameLength": 35, "maxFilenameLength": 250}}}
[04:25:40 PM] client/server >> {"Set": {"ready": {"isReady": false, "manuallyInitiated": false}}}
[04:25:40 PM] client/server << {"Set": {"ready": {"username": "jordan", "isReady": false, "manuallyInitiated": false}}}
```

No-GUI Logs (With debug enabled):
```
[16:46:54] Attempting to connect to syncplay.jordanplayz158.xyz:8999
[16:46:55] Could not send quit message: 'MpvPlayer' object has no attribute '_listener'
ERROR:	Could not load mpv: '__Listener' object has no attribute 'mpvpipe'
ERROR:	Media player error: "[Errno 111] Connection refused" The reason mpv cannot start may be due to the use of unsupported command line arguments or an unsupported version of mpv.
[16:46:55] client/server >> {"TLS": {"startTLS": "send"}}
[16:46:55] Attempting secure connection
[16:46:55] Successfully reached syncplay.jordanplayz158.xyz (2603:7081:2a3e:99ac:34b2:e73b:83f8:f750)
[16:46:55] client/server << {"TLS": {"startTLS": "true"}}
[16:46:55] Secure connection established (TLSv1.3)
[16:46:55] client/server >> {"Hello": {"username": "jordan", "password": "cd1a2c444a8517fe1eb25bbf809fa613", "room": {"name": "DITF"}, "version": "1.2.255", "realversion": "1.6.9", "features": {"sharedPlaylists": true, "chat": true, "featureList": true, "readiness": true, "managedRooms": true}}}
[16:46:55] client/server << {"Set": {"ready": {"username": "jordan", "isReady": null, "manuallyInitiated": false}}}
[16:46:55] client/server << {"Set": {"playlistChange": {"user": null, "files": []}}}
[16:46:55] client/server << {"Set": {"playlistIndex": {"user": null, "index": null}}}
[16:46:55] client/server << {"Hello": {"username": "jordan", "room": {"name": "DITF"}, "version": "1.6.9", "realversion": "1.6.9", "motd": "", "features": {"isolateRooms": false, "readiness": true, "managedRooms": true, "chat": true, "maxChatMessageLength": 150, "maxUsernameLength": 150, "maxRoomNameLength": 35, "maxFilenameLength": 250}}}
[16:46:55] Successfully connected to server
[16:46:55] client/server >> {"Set": {"ready": {"isReady": false, "manuallyInitiated": false}}}
[16:46:55] client/server << {"Set": {"ready": {"username": "jordan", "isReady": false, "manuallyInitiated": false}}}
[16:46:55] Connection with server lost, attempting to reconnect
```

**Comment by JordanPlayz158** [comment]
Looked into it and added debug messages to places in the code, it seems that the connection is refused to the custom made socket but.... the default mpvsocket can be connected to fine. Going to delve deeper into it, just reporting my findings

**Comment by JordanPlayz158** [comment]
Very sorry, It appears one of my extensions for MPV were overriding the ipc socket displayed by MPV, so this isn't an issue with MPV or SyncPlay. But perhaps to prevent this in the future we should use the `--no-config` (Was told this isn't possible as you guys bundle scripts), or maybe we can change config directory to non-existent directory and use command line arguments to pass everything or if we do have scripts, change mpv's directory it checks for configs to SyncPlay's own config folder

**Comment by JordanPlayz158** [comment]
Moved feature suggestion talk to #512
