### ISSUE TITLE
error when close the app

### ISSUE THREAD

**Issue by jiang-yuan** [Syncplay/syncplay#530]
**Describe the bug**
show error when close the app

**Version and platform:**
 - OS:  Windows 10 64-bit
 - Syncplay version and build type: 1.7.0 beta
 - Media player and version: mpv

**Additional context**
Unhandled Error
Traceback (most recent call last):
  File "twisted\internet\defer.pyc", line 477, in addCallbacks
    
  File "twisted\internet\defer.pyc", line 857, in _runCallbacks
    
  File "twisted\internet\base.pyc", line 510, in _continueFiring
    
  File "twisted\internet\base.pyc", line 762, in disconnectAll
    
--- <exception caught here> ---
  File "twisted\python\log.pyc", line 96, in callWithLogger
    
  File "twisted\python\log.pyc", line 80, in callWithContext
    
  File "twisted\python\context.pyc", line 117, in callWithContext
    
  File "twisted\python\context.pyc", line 82, in callWithContext
    
  File "twisted\internet\tcp.pyc", line 508, in connectionLost
    
  File "twisted\internet\tcp.pyc", line 326, in connectionLost
    
  File "twisted\protocols\tls.pyc", line 400, in connectionLost
    
  File "twisted\protocols\policies.pyc", line 114, in connectionLost
    
  File "twisted\internet\endpoints.pyc", line 159, in connectionLost
    
  File "twisted\application\internet.pyc", line 466, in connectionLost
    
  File "twisted\application\internet.pyc", line 659, in <lambda>
    
  File "automat\_methodical.pyc", line 244, in _clientDisconnected
    
  File "automat\_methodical.pyc", line 283, in __call__
    
  File "twisted\application\internet.pyc", line 779, in _wait
    
  File "twisted\application\internet.pyc", line 790, in _doWait
    
  File "syncplay\client.pyc", line 855, in retry
    
  File "syncplay\client.pyc", line 1634, in showMessage
    
  File "syncplay\client.pyc", line 1667, in showOSDMessage
    
  File "syncplay\players\mpv.pyc", line 133, in displayMessage
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 600, in wrapper
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 633, in command
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 330, in command
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 89, in send
    
builtins.BrokenPipeError: handle is closed

Unhandled Error
Traceback (most recent call last):
  File "twisted\internet\defer.pyc", line 477, in addCallbacks
    
  File "twisted\internet\defer.pyc", line 857, in _runCallbacks
    
  File "twisted\internet\base.pyc", line 510, in _continueFiring
    
  File "twisted\internet\base.pyc", line 762, in disconnectAll
    
--- <exception caught here> ---
  File "twisted\python\log.pyc", line 96, in callWithLogger
    
  File "twisted\python\log.pyc", line 80, in callWithContext
    
  File "twisted\python\context.pyc", line 117, in callWithContext
    
  File "twisted\python\context.pyc", line 82, in callWithContext
    
  File "twisted\internet\tcp.pyc", line 508, in connectionLost
    
  File "twisted\internet\tcp.pyc", line 326, in connectionLost
    
  File "twisted\protocols\tls.pyc", line 400, in connectionLost
    
  File "twisted\protocols\policies.pyc", line 114, in connectionLost
    
  File "twisted\internet\endpoints.pyc", line 159, in connectionLost
    
  File "twisted\application\internet.pyc", line 466, in connectionLost
    
  File "twisted\application\internet.pyc", line 659, in <lambda>
    
  File "automat\_methodical.pyc", line 244, in _clientDisconnected
    
  File "automat\_methodical.pyc", line 283, in __call__
    
  File "twisted\application\internet.pyc", line 779, in _wait
    
  File "twisted\application\internet.pyc", line 790, in _doWait
    
  File "syncplay\client.pyc", line 855, in retry
    
  File "syncplay\client.pyc", line 1634, in showMessage
    
  File "syncplay\client.pyc", line 1667, in showOSDMessage
    
  File "syncplay\players\mpv.pyc", line 133, in displayMessage
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 600, in wrapper
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 633, in command
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 330, in command
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 89, in send
    
builtins.BrokenPipeError: handle is closed

Unhandled error in Deferred:

Traceback (most recent call last):
  File "syncplay\vendor\qt5reactor.pyc", line 276, in iterate_qt
    
  File "syncplay\vendor\qt5reactor.pyc", line 363, in iterate
    
  File "twisted\internet\base.pyc", line 991, in runUntilCurrent
    
  File "twisted\internet\task.pyc", line 251, in __call__
    
--- <exception caught here> ---
  File "twisted\internet\defer.pyc", line 190, in maybeDeferred
    
  File "syncplay\client.pyc", line 1217, in __displayMessageOnOSD
    
  File "syncplay\client.pyc", line 1130, in <lambda>
    
  File "syncplay\client.pyc", line 1162, in _checkIfYouReAloneInTheRoom
    
  File "syncplay\client.pyc", line 1667, in showOSDMessage
    
  File "syncplay\players\mpv.pyc", line 133, in displayMessage
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 600, in wrapper
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 633, in command
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 330, in command
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 89, in send
    
builtins.BrokenPipeError: handle is closed

Unhandled Error
Traceback (most recent call last):
  File "twisted\internet\defer.pyc", line 477, in addCallbacks
    
  File "twisted\internet\defer.pyc", line 857, in _runCallbacks
    
  File "twisted\internet\base.pyc", line 510, in _continueFiring
    
  File "twisted\internet\base.pyc", line 762, in disconnectAll
    
--- <exception caught here> ---
  File "twisted\python\log.pyc", line 96, in callWithLogger
    
  File "twisted\python\log.pyc", line 80, in callWithContext
    
  File "twisted\python\context.pyc", line 117, in callWithContext
    
  File "twisted\python\context.pyc", line 82, in callWithContext
    
  File "twisted\internet\tcp.pyc", line 508, in connectionLost
    
  File "twisted\internet\tcp.pyc", line 326, in connectionLost
    
  File "twisted\protocols\tls.pyc", line 400, in connectionLost
    
  File "twisted\protocols\policies.pyc", line 114, in connectionLost
    
  File "twisted\internet\endpoints.pyc", line 159, in connectionLost
    
  File "twisted\application\internet.pyc", line 466, in connectionLost
    
  File "twisted\application\internet.pyc", line 659, in <lambda>
    
  File "automat\_methodical.pyc", line 244, in _clientDisconnected
    
  File "automat\_methodical.pyc", line 283, in __call__
    
  File "twisted\application\internet.pyc", line 779, in _wait
    
  File "twisted\application\internet.pyc", line 790, in _doWait
    
  File "syncplay\client.pyc", line 855, in retry
    
  File "syncplay\client.pyc", line 1634, in showMessage
    
  File "syncplay\client.pyc", line 1667, in showOSDMessage
    
  File "syncplay\players\mpv.pyc", line 133, in displayMessage
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 600, in wrapper
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 633, in command
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 330, in command
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 89, in send
    
builtins.BrokenPipeError: handle is closed

Unhandled Error
Traceback (most recent call last):
  File "twisted\internet\defer.pyc", line 477, in addCallbacks
    
  File "twisted\internet\defer.pyc", line 857, in _runCallbacks
    
  File "twisted\internet\base.pyc", line 510, in _continueFiring
    
  File "twisted\internet\base.pyc", line 762, in disconnectAll
    
--- <exception caught here> ---
  File "twisted\python\log.pyc", line 96, in callWithLogger
    
  File "twisted\python\log.pyc", line 80, in callWithContext
    
  File "twisted\python\context.pyc", line 117, in callWithContext
    
  File "twisted\python\context.pyc", line 82, in callWithContext
    
  File "twisted\internet\tcp.pyc", line 508, in connectionLost
    
  File "twisted\internet\tcp.pyc", line 326, in connectionLost
    
  File "twisted\protocols\tls.pyc", line 400, in connectionLost
    
  File "twisted\protocols\policies.pyc", line 114, in connectionLost
    
  File "twisted\internet\endpoints.pyc", line 159, in connectionLost
    
  File "twisted\application\internet.pyc", line 466, in connectionLost
    
  File "twisted\application\internet.pyc", line 659, in <lambda>
    
  File "automat\_methodical.pyc", line 244, in _clientDisconnected
    
  File "automat\_methodical.pyc", line 283, in __call__
    
  File "twisted\application\internet.pyc", line 779, in _wait
    
  File "twisted\application\internet.pyc", line 790, in _doWait
    
  File "syncplay\client.pyc", line 855, in retry
    
  File "syncplay\client.pyc", line 1634, in showMessage
    
  File "syncplay\client.pyc", line 1667, in showOSDMessage
    
  File "syncplay\players\mpv.pyc", line 133, in displayMessage
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 600, in wrapper
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 633, in command
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 330, in command
    
  File "syncplay\vendor\python_mpv_jsonipc\python_mpv_jsonipc.pyc", line 89, in send
    
builtins.BrokenPipeError: handle is closed

**Comment by Et0h** [comment]
Is this issue the same as https://github.com/Syncplay/syncplay/issues/571 ?
