### ISSUE TITLE
[AppImage] AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

### ISSUE THREAD

**Issue by Kcchouette** [Syncplay/syncplay#606]
**Describe the bug**
When trying to run the AppImage on Manjaro, I have a stacktrace and the GUI does not start

**To Reproduce**
1. Have the 1.7.0 AppImage
2. `chmod +x` and run it `./Syncplay-1.7.0-x86_64.AppImage`
3. See the error

```
$ ./Syncplay-1.7.0-x86_64.AppImage 
Traceback (most recent call last):
  File "/tmp/.mount_Syncpl3vPoYa/usr/bin/syncplay", line 8, in <module>
    sys.exit(main())
  File "/tmp/.mount_Syncpl3vPoYa/usr/conda/lib/python3.10/site-packages/syncplay/ep_client.py", line 8, in main
    SyncplayClientManager().run()
  File "/tmp/.mount_Syncpl3vPoYa/usr/conda/lib/python3.10/site-packages/syncplay/clientManager.py", line 9, in run
    config = ConfigurationGetter().getConfiguration()
  File "/tmp/.mount_Syncpl3vPoYa/usr/conda/lib/python3.10/site-packages/syncplay/ui/ConfigurationGetter.py", line 519, in getConfiguration
    from syncplay.vendor import qt5reactor
  File "/tmp/.mount_Syncpl3vPoYa/usr/conda/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/tmp/.mount_Syncpl3vPoYa/usr/conda/lib/python3.10/site-packages/syncplay/vendor/qt5reactor.py", line 111, in <module>
    from twisted.internet import posixbase
  File "/tmp/.mount_Syncpl3vPoYa/usr/conda/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/tmp/.mount_Syncpl3vPoYa/usr/conda/lib/python3.10/site-packages/twisted/internet/posixbase.py", line 16, in <module>
    from twisted.internet import error, tcp, udp
  File "/tmp/.mount_Syncpl3vPoYa/usr/conda/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/tmp/.mount_Syncpl3vPoYa/usr/conda/lib/python3.10/site-packages/twisted/internet/tcp.py", line 38, in <module>
    from twisted.internet._newtls import (
  File "/tmp/.mount_Syncpl3vPoYa/usr/conda/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/tmp/.mount_Syncpl3vPoYa/usr/conda/lib/python3.10/site-packages/twisted/internet/_newtls.py", line 18, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/tmp/.mount_Syncpl3vPoYa/usr/conda/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/tmp/.mount_Syncpl3vPoYa/usr/conda/lib/python3.10/site-packages/twisted/protocols/tls.py", line 42, in <module>
    from OpenSSL.SSL import Connection, Error, SysCallError, WantReadError, ZeroReturnError
  File "/tmp/.mount_Syncpl3vPoYa/usr/conda/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/tmp/.mount_Syncpl3vPoYa/usr/conda/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/tmp/.mount_Syncpl3vPoYa/usr/conda/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/tmp/.mount_Syncpl3vPoYa/usr/conda/lib/python3.10/site-packages/OpenSSL/crypto.py", line 3268, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
```

**Expected behavior**
Working, like the 1.6.9 appimage version (1.6.9 is still working and does not have this error)

**Version and platform:**
 - OS: Manjaro, updated as the date of 12 may 2023
 - Syncplay version and build type: 1.7.0 AppImage
 - Media player and version:  MPV

**Comment by Et0h** [comment]
I am closing this issue because Syncplay has now discontinued support for AppImages. See: https://github.com/Syncplay/syncplay/issues/643 for more details. If an issue recurs with Deb package or Tarball then please re-open this comment and let us know of the details.
