### ISSUE TITLE
macOS 10.13 launch crash: partially initialized module 'syncplay.vendor.Qt' has no attribute 'QtGui' 

### ISSUE THREAD

**Issue by xrisk** [Syncplay/syncplay#621]
**Describe the bug**
Syncplay crashes on launch. This doesn’t happen with Syncplay 1.6.9.

```
/Applications/Syncplay.app/Contents/MacOS/syncplay
Traceback (most recent call last):
  File "/Applications/Syncplay.app/Contents/Resources/__boot__.py", line 161, in <module>
    _run()
  File "/Applications/Syncplay.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Applications/Syncplay.app/Contents/Resources/syncplayClient.py", line 14, in <module>
    from syncplay import ep_client
  File "/Applications/Syncplay.app/Contents/Resources/lib/python3.10/syncplay/ep_client.py", line 3, in <module>
    from syncplay.clientManager import SyncplayClientManager
  File "/Applications/Syncplay.app/Contents/Resources/lib/python3.10/syncplay/clientManager.py", line 2, in <module>
    from syncplay import ui
  File "/Applications/Syncplay.app/Contents/Resources/lib/python3.10/syncplay/ui/__init__.py", line 9, in <module>
    from syncplay.ui.gui import MainWindow as GraphicalUI
  File "/Applications/Syncplay.app/Contents/Resources/lib/python3.10/syncplay/ui/gui.py", line 21, in <module>
    from syncplay.vendor import Qt
  File "/Applications/Syncplay.app/Contents/Resources/lib/python3.10/syncplay/vendor/Qt.py", line 2029, in <module>
    _install()
  File "/Applications/Syncplay.app/Contents/Resources/lib/python3.10/syncplay/vendor/Qt.py", line 2007, in _install
    our_submodule = getattr(Qt, name)
AttributeError: partially initialized module 'syncplay.vendor.Qt' has no attribute 'QtGui' (most likely due to a circular import)
2023-07-09 20:16:50.356 syncplay[32496:1446665] Launch error
2023-07-09 20:16:50.356 syncplay[32496:1446665] Launch error
See the py2app website for debugging launch issues
```

In the changelog, I see this entry for 1.7.0: "We have discontinued support for the legacy release of macOS as the relevant versions of the OS have reached end of life (EOL).”

Is support for macOS 10.13 discontinued? If so, can we fix the download link which says "MacOS (10.12+) disk image"

**To Reproduce**
1. Start Syncplay

**Screenshots**

![image](https://github.com/Syncplay/syncplay/assets/10669859/04c82f01-f28e-45b9-95cb-456cff90868d)

**Version and platform:**
 - OS: macOS 10.13
 - Syncplay version and build type: 1.7.0 release
 - Media player and version:  vlc

**Comment by albertosottile** [comment]
In version 1.7.0 we switched to pyside6/Qt 6 which [indeed does not support](https://doc.qt.io/qt-6.2/supported-platforms.html#macos) macOS 10.13 . 

@Et0h Given that the restriction comes from an upstream dependency, I guess our only course of action is indeed to adjust the descriptions on the website.

**Comment by Et0h** [comment]
> In version 1.7.0 we switched to pyside6/Qt 6 which [indeed does not support](https://doc.qt.io/qt-6.2/supported-platforms.html#macos) macOS 10.13 .
> 
> @Et0h Given that the restriction comes from an upstream dependency, I guess our only course of action is indeed to adjust the descriptions on the website.

Yes, as we use PySide/Qt6 we are limited to what is supported upstream.

I've updated https://syncplay.pl/syncplay-1-7-0-final/ to change it from MacOS 10.12+ to MacOS 10.14+ and advise those on MacOS 10.11-12 to [use Sycplay 1.6.9](https://syncplay.pl/syncplay-1-6-9/).

Side note: According to https://endoflife.date/macos the earliest version of macOS still being supported by Apple is macOS 11 (Big Sur) which is also the earliest version supported in Qt 6.5 LTS. Syncplay does not deliberately remove support for older operating systems or media players but naturally as we update our dependencies and build environment we will progressively lose support for older set-ups and we do not explicitly commit ourselves to supporting software that has reached End of Life. People who want to use older software can typically use older versions of Syncplay as we try to main protocol backwards and forwards compatibility, but of course users who use software that no longer gets security updates does so at their own risk.
