### ISSUE TITLE
Fails to launch, AttributeError: module 'syncplay.vendor.Qt' has no attribute 'QtGui'

### ISSUE THREAD

**Issue by GauravKishore** [Syncplay/syncplay#635]
**Describe the bug**
Syncplay fails to launch, logs contain an attribute error:

```
Traceback (most recent call last):
  File "syncplayClient.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "syncplay\ep_client.pyc", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "syncplay\clientManager.pyc", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "syncplay\ui\__init__.pyc", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "syncplay\ui\gui.pyc", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "syncplay\vendor\Qt.pyc", line 2029, in <module>
  File "syncplay\vendor\Qt.pyc", line 2007, in _install
AttributeError: module 'syncplay.vendor.Qt' has no attribute 'QtGui'
```

**Version and platform:**
 - Windows 11, 64 bit
 - Syncplay 1.7.0 (installed with Windows installer into %APPDATA%)

**Comment by Et0h** [comment]
I've tried running Syncplay.exe and SyncplayConsole.exe from the portable version of Syncplay 1.7.1 at https://github.com/Syncplay/syncplay/actions/runs/6488079163 (current GIT HEAD) on fresh VM installs of Windows 11 and they all work once [vc_redist.x86.exe](https://aka.ms/vs/17/release/vc_redist.x86.exe) is installed.

**Comment by GauravKishore** [comment]
1.7.1 looks like it works for me, thanks! Closing issue.
