### ISSUE TITLE
Syncplay doesn't work when built from source

### ISSUE THREAD

**Issue by astridbunny** [Syncplay/syncplay#644]
**Describe the bug**
Syncplay does not start. 

```
Traceback (most recent call last):
  File "/usr/bin/syncplay", line 16, in <module>
    from syncplay import ep_client
  File "/usr/lib/syncplay/syncplay/ep_client.py", line 3, in <module>
    from syncplay.clientManager import SyncplayClientManager
  File "/usr/lib/syncplay/syncplay/clientManager.py", line 4, in <module>
    from syncplay.ui.ConfigurationGetter import ConfigurationGetter
  File "/usr/lib/python3.12/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/syncplay/syncplay/ui/ConfigurationGetter.py", line 8, in <module>
    from configparser import SafeConfigParser, DEFAULTSECT
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/usr/lib/python3.12/configparser.py). Did you mean: 'RawConfigParser'?
```

**To Reproduce**
`sudo make install` then `syncplay`

**Version and platform:**
 - OS: Void Linux
 - Syncplay version and build type: 1.7.1-RC1

**Comment by Et0h** [comment]
Syncplay 1.7.1-RC1 was released on the 19th of September.

Subsequent to this PR #636 was accepted on the 11th of October which moved from SafeConfigParser to ConfigParser to support 3.12.

As such, moving to GIT HEAD should hopefully resolve the issue.
