### ISSUE TITLE
Crashes on launch: AttributeError: partially initialized module 'syncplay.vendor.Qt' has no attribute 'QtGui' (most likely due to a circular import)

### ISSUE THREAD

**Issue by reboot-mk** [Syncplay/syncplay#653]
**Describe the bug**
```
% syncplay --no-gui -a syncplay.pl:8996 -n lise -r test --player-path /usr/bin/mpv
Traceback (most recent call last):
  File "/usr/bin/syncplay", line 16, in <module>
    from syncplay import ep_client
  File "/usr/lib/syncplay/syncplay/ep_client.py", line 3, in <module>
    from syncplay.clientManager import SyncplayClientManager
  File "/usr/lib/syncplay/syncplay/clientManager.py", line 2, in <module>
    from syncplay import ui
  File "/usr/lib/syncplay/syncplay/ui/__init__.py", line 11, in <module>
    from syncplay.ui.gui import MainWindow as GraphicalUI
  File "/usr/lib/syncplay/syncplay/ui/gui.py", line 21, in <module>
    from syncplay.vendor import Qt
  File "/usr/lib/syncplay/syncplay/vendor/Qt.py", line 2029, in <module>
    _install()
  File "/usr/lib/syncplay/syncplay/vendor/Qt.py", line 2007, in _install
    our_submodule = getattr(Qt, name)
                    ^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'syncplay.vendor.Qt' has no attribute 'QtGui' (most likely due to a circular import)

```

**To Reproduce**
1. Start syncplay.

**Expected behavior**
Syncplay starts normally.

**Version and platform:**
 - OS: Arch Linux 6.6.8-zen1-1-zen
 - Syncplay version and build type: 1.7.1-2
 - Media player and version: v0.37.0

**Additional context**
I'm a bit puzzled as to why I'm getting this error even when I'm not using the GUI... It even pops up when using -v or -h.

**Comment by Et0h** [comment]
On line 12 of `/syncplay/ui/__init__.py` try changing:
`except ImportError:`

to:
`except (ImportError, AttributeError) as e:`
and let me know if that resolves the issue.

**Comment by reboot-mk** [comment]
This worked, thank you!!

**Comment by Et0h** [comment]
Glad it worked. I plan to make those change to the main Syncplay repo to fix the issue for others as well.
