### ISSUE TITLE
AttributeError: module 'syncplay.vendor.Qt' has no attribute 'QtGui' [Windows10, conda]

### ISSUE THREAD

**Issue by Voodoo-MAN** [Syncplay/syncplay#676]
Traceback (most recent call last):
  File "syncplayClient.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "syncplay\ep_client.pyc", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "syncplay\clientManager.pyc", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "syncplay\ui\__init__.pyc", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "syncplay\ui\gui.pyc", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "syncplay\vendor\Qt.pyc", line 2029, in <module>
  File "syncplay\vendor\Qt.pyc", line 2007, in _install
AttributeError: module 'syncplay.vendor.Qt' has no attribute 'QtGui'

I use:
Windows 10>
Anaconda>
Python 3.11.5;
The paths are registered, but I get this error. It is noteworthy that I received it before installing python and registering paths for it. Another person without paths in variable environments started up fine on Windows 10. Please help me with this problem. Thank you.

**Comment by Et0h** [comment]
I don't understand why you are running Syncplay using Anaconda.

My guess as to the error is that you do not have a compatible version of PySide installed. Does Syncplay work fine if you run it in --no-gui mode?
